;Task 5
(define (curry f)
	(lambda (n1)
		(lambda (n2)
			(lambda (n3)
				(lambda (n4)
					(f n1 n2 n3 n4)
					)
				)
			)
		)
	)
(define (main)
	(setPort (open (getElement ScamArgs 1) 'read))
	(define arg1 (eval (readExpr) this))
	(define arg2 (readExpr))
	(define arg3 (readExpr))
	(define arg4 (readExpr))
	(define arg5 (readExpr))
	(println "(((((curry " arg1 ") " arg2 ") " arg3 ") " arg4 ") " arg5 ") is " (((((curry arg1) arg2) arg3) arg4) arg5))
	)